/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class addiLib */

#ifndef _ADDILIB
#define _ADDILIB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     addiLib
 * Method:    fft
 * Signature: ()V
 */
JNIEXPORT jobjectArray JNICALL Java_com_addi_toolbox_general_fft_fftNative
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

JNIEXPORT jint JNICALL Java_com_addi_toolbox_general_fft_fftCleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
